version: '3.0'

services:
    db:
        image: mariadb:10
        container_name: db
        restart: unless-stopped
        env_file: .env
        volumes:
            - database:/var/lib/mysql
            - ./mariadb:/docker-entrypoint-initdb.d
        networks:
            - proxy-network

    nginx-proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: nginx-proxy
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - proxy-network

    nginx-proxy-le:
        depends_on:
            - nginx-proxy
        image: jrcs/letsencrypt-nginx-proxy-companion:latest
        container_name: nginx-proxy-le
        restart: unless-stopped
        environment:
            NGINX_PROXY_CONTAINER: nginx-proxy
        volumes:
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam:ro
            - certs:/etc/nginx/certs
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - proxy-network

    wp-site1:
        depends_on:
            - db
            - nginx-proxy-le
        image: wordpress:5-php7.2
        container_name: wp-site1
        restart: unless-stopped
        env_file: .env
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: ${SITE1_DB_NAME}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            VIRTUAL_HOST: ${SITE1_HOST_NAME}
            VIRTUAL_PORT: 443
            LETSENCRYPT_HOST: ${SITE2_HOST_NAME}
        volumes:
            - wp-site1:/var/www/html
        networks:
            - proxy-network

    wp-site2:
        depends_on:
            - db
            - nginx-proxy-le
        image: wordpress:5-php7.2
        container_name: wp-site2
        restart: unless-stopped
        env_file: .env
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: ${SITE2_DB_NAME}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            VIRTUAL_HOST: ${SITE2_HOST_NAME}
            VIRTUAL_PORT: 443
            LETSENCRYPT_HOST: ${SITE2_HOST_NAME}
        volumes:
            - wp-site2:/var/www/html
        networks:
            - proxy-network

networks:
    proxy-network:
        driver: bridge

volumes:
    database:
    conf:
    vhost:
    html:
    dhparam:
    certs:
    wp-site1:
    wp-site2: